In [ ]:
#Import libraries


In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:

df = pd.read_csv('weather_data.csv')

In [5]:
df.head()

YEAR    JUN    JUL    AUG    SEP
0  1901  111.0  243.2  273.6  124.6
1  1902  109.0  282.8  201.8  201.0
2  1903  117.0  292.0  271.7  200.9
3  1904  165.2  263.1  205.2  131.7
4  1905   92.3  254.9  201.4  180.0

In [6]:
X = df.iloc[:, 1:4].values

In [7]:
X

array([[111. , 243.2, 273.6],
       [109. , 282.8, 201.8],
       [117. , 292. , 271.7],
       [165.2, 263.1, 205.2],
       [ 92.3, 254.9, 201.4],
       [177.6, 284.8, 248.2],
       [153.1, 224.4, 310.9],
       [126.5, 325.3, 313.2],
       [206.6, 307.8, 234.1],
       [212. , 246.5, 288.7],
       [193.2, 164. , 215.4],
       [106.7, 330.6, 262.5],
       [214.2, 269.3, 194.6],
       [156.5, 351.3, 242.2],
       [157. , 231.6, 230.6],
       [232.3, 270.6, 313.7],
       [232.9, 286. , 297.1],
       [212.7, 187.5, 249.6],
       [195.2, 309.7, 290.6],
       [163.7, 297.5, 193.4],
       [192.3, 294.1, 277.9],
       [205.3, 318.3, 220.1],
       [101.9, 340. , 276.7],
       [134.6, 331.1, 258.7],
       [204.2, 305.7, 237.8],
       [ 97.5, 320.1, 336.1],
       [176.7, 349.3, 259.3],
       [178.6, 304.8, 233.4],
       [194.4, 297.4, 244.3],
       [180.2, 291.3, 213.3],
       [132.6, 321.1, 308.2],
       [141.6, 332.7, 239.3],
       [215.5, 283.9, 316.2],
       [21

In [8]:
y = df.iloc[:, -1].values

In [9]:
y

array([124.6, 201. , 200.9, 131.7, 180. , 183.1, 196.6, 152.9, 162.1,
       185.3, 183.4, 119.3, 109.6, 194.2, 174.7, 200. , 282.5, 113.3,
       163. , 123.1, 205.1, 204.4, 175.4, 239.2, 139.9, 211.3, 172.4,
       145.9, 125.3, 174.9, 191. , 182.5, 212.7, 166.6, 186.8, 195. ,
       175.4, 170.8, 157.7, 125.8, 156.1, 182. , 213. , 156.9, 214.2,
       144.7, 240.5, 178.3, 226.5, 204.6, 124. , 119.1, 178. , 246.9,
       219.5, 165.7, 132.2, 230.7, 237.2, 181.8, 236.2, 210.8, 166.8,
       199.5, 131. , 147.9, 172.6, 128.9, 175.9, 216.1, 150.6, 129.9,
       185.9, 144.6, 227. , 143.5, 148.8, 163.4, 137.6, 146.1, 186.8,
       126.2, 251.9, 145.2, 152.5, 125.5, 152. , 218.3, 164.3, 197.6,
       136.6, 168. , 210.9, 150. , 181. , 148.8, 152.4, 207.6, 188.8,
       135.5, 110.3, 139.1, 181.6, 124. , 201.2, 181.5, 215.7, 168.3,
       143.3, 198.4, 192.8, 199.4, 155.1, 190.1, 131.7, 168.8, 153. ,
       132.3, 260.4])

In [10]:
y.reshape(-1, 1) 

array([[124.6],
       [201. ],
       [200.9],
       [131.7],
       [180. ],
       [183.1],
       [196.6],
       [152.9],
       [162.1],
       [185.3],
       [183.4],
       [119.3],
       [109.6],
       [194.2],
       [174.7],
       [200. ],
       [282.5],
       [113.3],
       [163. ],
       [123.1],
       [205.1],
       [204.4],
       [175.4],
       [239.2],
       [139.9],
       [211.3],
       [172.4],
       [145.9],
       [125.3],
       [174.9],
       [191. ],
       [182.5],
       [212.7],
       [166.6],
       [186.8],
       [195. ],
       [175.4],
       [170.8],
       [157.7],
       [125.8],
       [156.1],
       [182. ],
       [213. ],
       [156.9],
       [214.2],
       [144.7],
       [240.5],
       [178.3],
       [226.5],
       [204.6],
       [124. ],
       [119.1],
       [178. ],
       [246.9],
       [219.5],
       [165.7],
       [132.2],
       [230.7],
       [237.2],
       [181.8],
       [236.2],
       [210.8],
       [

In [11]:
from sklearn.pipeline import make_pipeline


In [12]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()

In [13]:
X = sc_X.fit_transform(X)

In [14]:
y = sc_y.fit_transform(y.reshape(-1,1))

In [24]:
from sklearn.model_selection import train_test_split

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.22)

In [33]:
from sklearn.svm import SVR

In [34]:
regressor = SVR(kernel = 'rbf')

In [35]:
regressor.fit(X,y)

C:\Users\naveen\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVR()

In [36]:
y_pred = regressor.predict(X_test)

In [37]:
y_pred = sc_y.inverse_transform(y_pred)

In [38]:
df = pd.DataFrame({'Real Values':sc_y.inverse_transform(y_test.reshape(-1)), 'Predicted Values':y_pred})


In [39]:
df

Real Values  Predicted Values
0         211.3        207.699845
1         178.3        181.899511
2         197.6        170.985630
3         162.1        156.985827
4         226.5        182.986270
5         129.9        146.397402
6         182.5        193.498210
7         192.8        178.930414
8         146.1        155.898099
9         181.6        173.070729
10        156.1        141.588855
11        204.4        165.363206
12        145.2        153.360604
13        128.9        182.451781
14        166.8        197.350134
15        198.4        181.619280
16        170.8        170.329844
17        148.8        184.429348
18        180.0        169.286905
19        137.6        141.210962
20        126.2        163.627703
21        199.5        180.820810
22        132.3        155.238791
23        182.0        173.912543
24        152.0        148.374324
25        168.0        180.930717
26        119.3        183.312989